# Generated by Django 2.1.9 on 2019-06-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rate_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(related_name='recipes_created', to='recipes.Recipe'),
        ),
    ]
