# Generated by Django 2.1.9 on 2019-06-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190614_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(to='recipes.Recipe'),
        ),
    ]
